version: "3"

services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
    networks:
      - dpong_network

  player_1:
    build: .
    environment:
      - PLAYER_SIDE=left
      - DISPLAY=${DISPLAY}
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - etcd
    networks:
      - dpong_network

  player_2:
    build: .
    environment:
      - PLAYER_SIDE=right
      - DISPLAY=${DISPLAY}
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - etcd
    networks:
      - dpong_network

networks:
  dpong_network:
    driver: bridge
